name: Order TestFilght Link Status

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      python_version: ${{ github.event.inputs.python_version }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11.1'
          architecture: x64

      - name: Checkout main -> status_ordered
        run: |
          git config --global user.email "github_bot@noreply.github.com"
          git config --global user.name "github_bot"

      - name: Order TestFilght Link Status
        run: |
          curl https://raw.githubusercontent.com/pluwen/awesome-testflight-link/main/db/sqlite3.db -o db/sqlite3.db
          git_diff=`git diff`
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          python scripts/order_status.py

      - name: Git commit && push
        run: |
          git_diff=`git diff`
          if [ -z "$git_diff" ]; then echo "Nothing Changed";exit; fi
          git add .
          git commit -m "Github Action Auto Updated - `date`"
          git push origin main
